name: Conan

'on':
    pull_request:
    push:
        branches:
          - master
          - develop
          - feature/**

env:
    UBSAN_OPTIONS: print_stacktrace=1

jobs:
    build:
        runs-on: ${{ matrix.os }}
        name: '${{ matrix.os }} ({{ matrix.build-type }})'
        strategy:
            fail-fast: false
            matrix:
                include:
                  - os: ubuntu-22.04
                    conanflags: ''
                    build-type: Release
                  - os: ubuntu-22.04
                    conanflags: ''
                    build-type: Debug
                  - os: macos-latest
                    conanflags: '-o python_path=python3.11'
                    build-type: Release

        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
                fetch-depth: 0

          - name: Install Ubuntu packages
            if: matrix.os == 'ubuntu-22.04'
            run: |
                sudo apt-get install -y gcc g++ cmake wget git python3 python3-pip python3-venv

          - name: Install MacOS packages
            if: matrix.os == 'macos-latest'
            run: |
                brew update
                brew install postgresql
                brew install libiconv  # https://stackoverflow.com/questions/57734434/libiconv-or-iconv-undefined-symbol-on-mac-osx
                brew install python@3.11

          - name: Install common packages
            run: |
                pip install "conan==2.8.0"
                pip install numpy
                conan profile detect
                conan profile show

          - name: Run conan
            run: |
                conan create . --build=missing --settings=build_type=${{matrix.build-type}} -s:a compiler.cppstd=17 -pr:b=default ${{matrix.conanflags}} -tf conan/test_package/
